import type { ExperienceItem } from "../../types/experience";

export const MOCK_EXPERIENCES: ExperienceItem[] = [
  {
    id: 1,
    type: "프로젝트",
    name: "경식이 AI 전화 서비스",
    org: "사이드 프로젝트",
    period: "2025.03 ~ 2025.08",
    role: "PM / 기획",
    importance: "높음",
    important: true,
    competencies: ["문제해결", "기획력"],
    keywords: ["문제해결", "사용자조사", "기획력"],
    status: "완료",
    missing: [],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "어제",
    fields: {
      ptype: "사이드 프로젝트",
      org: "사이드 프로젝트",
      period: "2025.03 ~ 2025.08",
      role: "PM / 기획",
      teamSize: "4명",
      stack: "Figma, Notion",
      overview: "고령층 여가 문제 해결 AI 전화 서비스",
      problem: "고령층의 사회적 고립 문제",
      myRole: "PM 및 사용자 인터뷰 진행",
      result: "베타 만족도 4.5/5",
      __body:
        "고령층의 사회적 고립을 줄이기 위해 AI 전화 서비스를 기획했습니다.\n서비스 기획자로서 20명의 사용자 인터뷰를 주도하고 프로토타입을 3회 반복했습니다.\n베타 100명을 대상으로 한 테스트에서 만족도 4.5/5를 받았습니다.",
    },
  },
  {
    id: 2,
    type: "대외활동",
    name: "업비트 서포터즈",
    org: "업비트",
    period: "2024.08 ~ 2024.11",
    role: "콘텐츠 기획",
    importance: "보통",
    competencies: ["기획력", "소통"],
    keywords: ["기획력", "소통"],
    status: "작성중",
    missing: ["성과 정리"],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "3일 전",
    hasUnansweredAiQuestion: true,
    fields: {
      atype: "서포터즈",
      org: "업비트",
      period: "2024.08 ~ 2024.11",
      role: "콘텐츠 기획",
    },
  },
  {
    id: 3,
    type: "인턴",
    name: "여름 프론트엔드 인턴십",
    org: "픽디랩",
    period: "2025.07 ~ 2025.08",
    role: "프론트엔드",
    importance: "높음",
    important: true,
    competencies: ["실행력", "협업"],
    keywords: ["팀워크", "실행력"],
    status: "작성중",
    missing: ["수치 성과"],
    pinned: false,
    linkedExperienceIds: [],
    updatedAt: "방금 전",
    fields: {
      company: "픽디랩",
      dept: "서비스 개발팀",
      position: "프론트엔드",
      period: "2025.07 ~ 2025.08",
      empType: "인턴",
      tasks: "지원 대시보드 UI 구현",
    },
  },
  {
    id: 4,
    type: "교환학생",
    name: "파리정치대학 교환학생",
    org: "파리정치대학",
    period: "2024.02 ~ 2024.07",
    importance: "보통",
    competencies: ["글로벌"],
    keywords: ["글로벌", "팀워크"],
    status: "작성중",
    missing: [],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "1주 전",
    fields: {
      country: "프랑스",
      univ: "파리정치대학",
      period: "2024.02 ~ 2024.07",
      major: "정치·사회 데이터 분석",
    },
  },
  {
    id: 5,
    type: "수상",
    name: "부산대학교 IT융합 해커톤 우수상",
    org: "부산대학교",
    period: "2025.08",
    importance: "높음",
    important: true,
    competencies: ["문제해결", "협업"],
    keywords: ["문제해결", "협업"],
    status: "완료",
    missing: [],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "2주 전",
    fields: {
      award: "부산대학교 IT융합 해커톤 우수상",
      level: "우수상",
      host: "부산대학교",
      awardedAt: "2025.08",
      relation: "AI 추천 서비스 프로젝트와 연결",
    },
  },
  {
    id: 6,
    type: "자격증",
    name: "컴퓨터활용능력 1급",
    org: "대한상공회의소",
    period: "2025.02",
    importance: "보통",
    competencies: [],
    keywords: ["데이터 분석"],
    status: "완료",
    missing: [],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "3주 전",
    fields: {
      certificate: "컴퓨터활용능력 1급",
      grade: "1급",
      issuer: "대한상공회의소",
      issuedAt: "2025.02",
    },
  },
  {
    id: 7,
    type: "수강과목",
    name: "Digital Marketing",
    org: "고려대학교",
    period: "2024 2학기",
    importance: "낮음",
    competencies: ["기획력"],
    keywords: ["기획력", "데이터 분석"],
    status: "작성중",
    missing: [],
    pinned: false,
    linkedExperienceIds: [],
    updatedAt: "1개월 전",
    fields: {
      school: "고려대학교",
      semester: "2024 2학기",
      credit: "3학점",
      grade: "A0",
      skill: "마케팅 데이터 분석",
    },
  },
  {
    id: 8,
    type: "어학",
    name: "TOEIC 945",
    org: "ETS",
    period: "2025.01",
    importance: "보통",
    competencies: ["글로벌"],
    keywords: ["글로벌"],
    status: "완료",
    missing: [],
    pinned: true,
    linkedExperienceIds: [],
    updatedAt: "1개월 전",
    fields: {
      exam: "TOEIC",
      score: "945",
      issuer: "ETS",
      issuedAt: "2025.01",
      expireAt: "2027.01",
    },
  },
  {
    id: 9,
    type: "프로젝트",
    name: "고령층 인터뷰 경험",
    org: "사이드 프로젝트",
    period: "2025.04 ~ 2025.05",
    role: "리서처",
    importance: "보통",
    competencies: ["사용자조사"],
    keywords: ["사용자조사"],
    status: "병합 필요",
    missing: [],
    pinned: false,
    linkedExperienceIds: [1],
    updatedAt: "방금",
    hasMergeCandidate: true,
    fields: {
      org: "사이드 프로젝트",
      period: "2025.04 ~ 2025.05",
      role: "리서처",
      overview: "경식이 AI 전화 서비스와 연결되는 사용자 인터뷰 경험",
    },
  },
];
